### ISSUE TITLE
Abilility to run in background

### ISSUE THREAD

**Issue by vemv** [nrepl/lein-nrepl#3]
I was thinking that it'd be great to e.g. `lein do nrepl :in-background, some-other-long-running-task`.

That way I can use the same JVM process to run a nrepl server, and concurrently another long-running task. Saves resources basically.

Would it be a welcome feature? As conceived lein-nrepl seems a temporary library, but perhaps it can aspire to a bit more.

Can give a shot to a PR if the idea seems sound.

Cheers - Victor

**Comment by bbatsov** [comment]
Yeah, PRs welcome.

You know how temporary solutions often tend to stick around - especially if
they offer more flexibility over the “default” solution. :-)

There’s many easy wins on the horizon - support for passing configuration
via profiles is also something that we should probably tackle.
